[package]
name = "iscs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
nalgebra = "0.31.4"
rand = "0.8.5"
toml = "0.5.10"
tungstenite = "0.18.0"
