name = "default constellation"

[constellation]
altitude = 0.55e6
num_orbital_planes = 10
satellites_per_plane = 20
inclination = 0.6
max_connections = 4
connection_range = 1e10 # What's a good value for here? have to research

[simulation]
update_frequency = 10.0
simulation_speed = 5.0
connection_refresh_interval = 10.0