name = "default constellation"

[constellation]
altitude = 0.55e6
number_of_orbital_planes = 10
satellites_per_plane = 20
inclination = 0.6
max_connections = 4
connection_range = 1e10 # What's a good value for here? have to research

[simulation]
time_step = 1.0
starting_failure_rate = 0.0
connection_refresh_interval = 10.0