name = "Default"

[constellation]
altitude = 0.55e6
num_orbital_planes = 10
satellites_per_plane = 20
inclination = 60.0
max_connections = 4

[simulation]
update_frequency = 10.0
simulation_speed = 5.0
connection_refresh_interval = 10.0