name = "Iridium"

[constellation]
altitude = 0.781e6
num_orbital_planes = 6
satellites_per_plane = 11
inclination = 86.4
max_connections = 4
connection_range = 1e10

[simulation]
update_frequency = 10.0
simulation_speed = 5.0
connection_refresh_interval = 10.0
