name = "OneWeb"

[constellation]
altitude = 1.2e6
num_orbital_planes = 12
satellites_per_plane = 49
inclination = 1.507964
max_connections = 4
connection_range = 1e10

[simulation]
time_step = 1.0
connection_refresh_interval = 10.0
