name = "Starlink 2"

[constellation]
altitude = 0.55e6
num_orbital_planes = 24
satellites_per_plane = 66
inclination = 53.0
phasing = 13
max_connections = 4

[simulation]
update_frequency = 10.0
simulation_speed = 5.0
connection_refresh_interval = 10.0
