name = "Starlink1"

[constellation]
altitude = 1.15e6
num_orbital_planes = 32
satellites_per_plane = 50
inclination = 53
max_connections = 4
connection_range = 1e10

[simulation]
update_frequency = 10.0
simulation_speed = 5.0
connection_refresh_interval = 10.0
